services:
  - type: web
    name: ai-services-quickstart
    runtime: node
    buildCommand: npm install && npm --prefix playground install && npm --prefix playground run build
    startCommand: npm start
    plan: free
    envVars:
      - key: ZOOM_API_KEY
        sync: false
      - key: ZOOM_API_SECRET
        sync: false
      - key: AWS_ACCESS_KEY_ID
        sync: false
      - key: AWS_SECRET_ACCESS_KEY
        sync: false
      - key: AWS_SESSION_TOKEN
        sync: false
      - key: WEBHOOK_SECRET
        sync: false